### ISSUE TITLE
Frends.Salesforce.ExecuteQuery

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.Salesforce#1]
Task for executing of Salesforce queries.

Ask Jefim for concrete example for doing this, no need to go through SF docs - we already have an implementation in subprocess form.

Task parameters:
- Username/password/security token for authentication
- Use test login or normal login (different URLs on SF side for sandbox environments)
- Query itself

Task output:
- The content of HTTP response Body.records as array (in jtoken form).

Other:
- Lets aim for automated tests and having integration tests automated
- No performance tests needed, SF is the main bottleneck
- For authentication - would be nice to cache the bearer token for any additional use

**Comment by Svenskapojkarna** [comment]
Initial implementation of the task completed.
