### ISSUE TITLE
Unit tests are broken

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.Salesforce#15]
There has been a report that unit tests have started to fail by themselves. Quick investigation points to credentials being too old. Credentials reset did not fix the issue though. Needs further investigation from test Salesforce instance.

**Comment by sorvami** [comment]
Problem is in those salesforce tasks in frendstasktest env: https://frendstasktest.frendsapp.com/Process/List/Default/Default?desc=false&sortBy=name&filterCategory=Text&filterText=sa . Those tasks use this https://hiqfinlandoy2-dev-ed.my.salesforce.com/. Couple of those started to fail a  while ago.

**Comment by Svenskapojkarna** [comment]
Credentials update seems to have fixed the issue.
