### ISSUE TITLE
Salesforce password keeps resetting

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.Salesforce#16]
Test Salesforce password keeps resetting, which not an ideal situation for unit tests.
It should be investigated if the expiration time could be extended/removed.

**Comment by RikuVirtanen** [comment]
The password can be set to never expire by modifying the password policies of the System Administration profile. This change would affect to your user as well @Svenskapojkarna. Another way would be to clone that profile and set the password to never expire to the new one before adding the testuser to that profile. Which would be better in this case?

**Comment by RikuVirtanen** [comment]
Created new profile with setting password never expires and set it to the test user. This is now resolved.
