### ISSUE TITLE
References to Result-objects Body and access token don't work

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.Salesforce#9]
If you try to access values of Result-objects Body-property with dot-notation, Frends will throw an error, since object doesn't have properties for the return values. This happens since SF-tasks return the body as pure object. This should be changed so that the Body is returned as a JToken, so the content properties can be accessed.
![image](https://user-images.githubusercontent.com/36008914/168033047-633f0999-f733-41f8-b722-c4979fb71699.png)

Another issue is that if you try to use the access token returned from the task, Frends will throw an error that the property doesn't exist in Result-object. It would seem that the inheritance doesn't work, so it would be better to combine the Result-classes into one class and just return null for the Token-property if the user doesn't want to return the token.
![image](https://user-images.githubusercontent.com/36008914/168033483-7c27b409-c571-407e-82a0-1db0c09bfd97.png)

These issues are present in all SF-tasks currectly.

**Comment by helvertti** [comment]
Function fixes implemented.
